/**
 * electron-builder.cjs — Dynamic build configuration.
 *
 * Two packaging modes are controlled by the BUILD_MODE environment variable:
 *
 *   BUILD_MODE=local  (default)  Full build: bundles the embedded JRE and
 *                                Spring Boot JAR so the desktop app can run a
 *                                local backend.  Original behavior.
 *
 *   BUILD_MODE=remote            Lightweight build: omits the JRE/JAR
 *                                resources (~530 MB smaller on macOS).  The app
 *                                can only connect to a remote server — the
 *                                "local" connection option is hidden in the
 *                                splash UI.
 *
 * Branding is controlled by branding.config.json or BRAND_* env vars.
 * See scripts/branding.cjs for details.
 *
 * Windows "Programs and Features" (appwiz.cpl) fields are mapped as:
 *   DisplayName      ← productName  (brand.name)
 *   Publisher        ← brand.publisher / package.json author
 *   DisplayVersion   ← package.json version
 *   URLInfoAbout     ← nsis.uninstallUrlInfoAbout    (brand.aboutUrl)
 *   HelpLink         ← nsis.uninstallUrlHelp         (brand.supportUrl)
 *   URLUpdateInfo    ← nsis.uninstallUrlUpdateInfo   (brand.updateUrl)
 *   ARPREADME        ← nsis.uninstallUrlReadme       (brand.readmeUrl)
 *   Comments         ← package.json description      (brand.comments)
 *   EstimatedSize    ← auto-calculated by installer
 *
 * Usage:
 *   BUILD_MODE=remote npx electron-builder --mac
 *   npm run package:mac:remote
 *   BRAND_NAME=MyAI npm run package:mac:remote
 */
'use strict'

const fs = require('fs')
const path = require('path')
const { loadBrandConfig } = require('./scripts/branding.cjs')

const mode = process.env.BUILD_MODE === 'remote' ? 'remote' : 'local'
const brand = loadBrandConfig(__dirname)

// ---------------------------------------------------------------------------
// Emit brand constants into a NSIS include header.  The values are read by
// build/installer.nsh and written into the Windows Uninstall registry so
// that "Programs and Features" (appwiz.cpl) displays all the configured
// metadata dimensions (support/about/update/readme URLs + comments).
// ---------------------------------------------------------------------------
const buildDir = path.join(__dirname, 'build')
fs.mkdirSync(buildDir, { recursive: true })
fs.writeFileSync(
  path.join(buildDir, '_brand_nsis_defines.nsh'),
  [
    '; DO NOT EDIT — auto-generated by electron-builder.cjs from branding.config.json',
    `!define BRAND_APP_ID         "${escapeNsis(brand.appId)}"`,
    `!define BRAND_PUBLISHER      "${escapeNsis(brand.publisher)}"`,
    `!define BRAND_COMMENTS       "${escapeNsis(brand.comments)}"`,
    `!define BRAND_SUPPORT_URL    "${escapeNsis(brand.supportUrl)}"`,
    `!define BRAND_ABOUT_URL      "${escapeNsis(brand.aboutUrl)}"`,
    `!define BRAND_UPDATE_URL     "${escapeNsis(brand.updateUrl)}"`,
    `!define BRAND_README_URL     "${escapeNsis(brand.readmeUrl)}"`,
    '',
  ].join('\r\n'),
  'utf8'
)

/**
 * Escape a string for safe placement inside a NSIS "..." quoted literal.
 * Doubles-up embedded quotes "$\quot" so `"foo \" bar"` → `"foo $\quot$\quot bar"`.
 * @param {string} s Input string (may contain quotes/backslashes).
 * @returns {string} Escaped string safe inside NSIS double-quoted literals.
 */
function escapeNsis(s) {
  return String(s == null ? '' : s)
    .replace(/\$/g, '$$')
    .replace(/"/g, '$\\quot$\\quot')
    .replace(/\r?\n/g, ' $\\r$\\n ')
}

// Derive a short slug from the brand name for artifact file names.
// "MyAI" → "MyAI", "Cool App" → "Cool_App"
const brandSlug = brand.name.replace(/\s+/g, '_')

// Parse GitHub URL for publish config (owner/repo)
let githubOwner = 'sns'
let githubRepo = 'SnSclaw'
const ghMatch = brand.githubUrl.match(/github\.com\/([^/]+)\/([^/]+)/)
if (ghMatch) {
  githubOwner = ghMatch[1]
  githubRepo = ghMatch[2]
}

/** @type {import('electron-builder').Configuration} */
const config = {
  appId: brand.appId,
  productName: brand.name,
  copyright: brand.copyright,
  directories: { output: 'release' },
  // extraMetadata is written into the bundled app's package.json at pack time.
  // It ensures that app.getVersion() / app.getName() / electron-updater
  // Publisher detection all read from the same authoritative source.
  extraMetadata: {
    author: brand.publisher,
    description: brand.comments,
    homepage: brand.homepageUrl,
    bugs: {
      url: brand.supportUrl,
    },
    repository: {
      type: 'git',
      url: brand.githubUrl,
    },
  },
  publish: [
    {
      provider: 'github',
      owner: githubOwner,
      repo: githubRepo,
    },
  ],
  files: ['dist-electron', 'dist'],
  afterPack: 'scripts/trim-playwright-driver.cjs',

  // ⚠️ ws (WebSocket) 的 peer dependencies — bufferutil / utf-8-validate —
  // 是 C++ 原生 addon (.node 文件)，必须从 asar 中解包才能由 Node 加载器
  // 通过 LoadLibrary 装载。即便用户未安装它们，ws 也会 fallback 到纯 JS
  // 实现，所以这里的解包声明对两种情况都是安全的。
  // 参见 https://github.com/websockets/ws#opt-in-for-performance
  asarUnpack: [
    'node_modules/ws/**/*',
    'node_modules/bufferutil/**/*',
    'node_modules/utf-8-validate/**/*',
  ],

  // extraResources: only bundle JRE + JAR in local mode.
  // In remote mode this array is empty — the packaged app contains only the
  // Electron + Vue shell, cutting ~530 MB from the installer.
  extraResources:
    mode === 'local'
      ? [
          {
            from: 'resources/jre/${os}-${arch}/',
            to: 'jre/',
            filter: ['**/*'],
          },
          {
            from: 'resources/app.jar',
            to: 'app.jar',
          },
        ]
      : [],

  mac: {
    category: 'public.app-category.productivity',
    target: [
      { target: 'dmg', arch: ['arm64', 'x64'] },
      { target: 'zip', arch: ['arm64', 'x64'] },
    ],
    icon: 'build/icon.icns',
    hardenedRuntime: true,
    gatekeeperAssess: false,
    entitlements: 'build/entitlements.mac.plist',
    entitlementsInherit: 'build/entitlements.mac.inherit.plist',
    // Differentiate installers so users can tell local vs remote builds apart.
    artifactName:
      mode === 'remote'
        ? `${brandSlug}_Remote_${'$'}{version}_${'$'}{arch}.${'$'}{ext}`
        : `${brandSlug}_${'$'}{version}_${'$'}{arch}.${'$'}{ext}`,
  },

  dmg: {
    contents: [
      { x: 130, y: 220 },
      { x: 410, y: 220, type: 'link', path: '/Applications' },
    ],
    title: `${brand.name} ${'$'}{version}`,
  },

  win: {
    target: [
      { target: 'nsis', arch: 'x64' },
      // { target: 'nsis', arch: 'arm64' },  // disabled: user needs only x64 for Win10
    ],
    icon: 'build/icon.ico',
    forceCodeSigning: false,
    // NOTE: Publisher display in Add/Remove Programs is handled by two layers:
    //   1) extraMetadata.author  → written into bundled app's package.json
    //      (read by electron-updater + default uninstall reg write)
    //   2) build/installer.nsh customInstall → explicit WriteRegStr
    //      overwrites Publisher + all URL/comments fields in HKLM/HKCU both views.
    // win.publisherName was deprecated in electron-builder 25.x and is NOT
    // needed here in the forceCodeSigning=false (unsigned) path.
    artifactName:
      mode === 'remote'
        ? `${brandSlug}_Remote_${'$'}{version}_${'$'}{arch}_Setup.${'$'}{ext}`
        : `${brandSlug}_${'$'}{version}_${'$'}{arch}_Setup.${'$'}{ext}`,
  },

  nsis: {
    oneClick: false,
    // perMachine=true：装到 C:\Program Files\SnSclaw（需要 UAC 提权一次）。
    // 应用运行时所有可写状态（H2 库、connection.json、local-tools.json）都在
    // app.getPath('userData') = %APPDATA%，不写安装目录，所以只读的 Program Files 没问题。
    perMachine: true,
    allowToChangeInstallationDirectory: true,
    deleteAppDataOnUninstall: false,
    installerIcon: 'build/icon.ico',
    uninstallerIcon: 'build/icon.ico',
    installerHeaderIcon: 'build/icon.ico',
    createDesktopShortcut: true,
    createStartMenuShortcut: true,
    // ===== Windows "程序和功能"控制面板元数据 =====
    // 卸载列表中的显示名（默认 = productName + version），显式声明可保持中文一致
    uninstallDisplayName: `${brand.name}`,
    // ⚠️ 不要设 menuCategory。perMachine 的默认安装目录是
    //    $PROGRAMFILES64\<menuCategory>\<APP_FILENAME>，设了它就会变成
    //    C:\Program Files\SnSclaw\SnSclaw。开始菜单快捷方式放根级即可（单应用）。
    // ⚠️ 以下卸载面板 URL 元数据 (HelpLink / URLInfoAbout / URLUpdateInfo / ARPREADME
    //     + Comments) 在 electron-builder 25.1.8 中尚未作为 nsis.* 配置字段暴露。
    //     我们通过 build/installer.nsh 自定义 NSIS include 脚本，在安装完成
    //     后通过 WriteRegStr 直接写入注册表。URL/文本值由下面的宏注入：
    include: 'build/installer.nsh',
  },

  linux: {
    target: ['AppImage'],
    icon: 'build/icon.png',
    category: 'Utility',
    artifactName:
      mode === 'remote'
        ? `${brandSlug}_Remote_${'$'}{version}.${'$'}{ext}`
        : `${brandSlug}_${'$'}{version}.${'$'}{ext}`,
  },
}

module.exports = config
